apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
    tier: backend
    project: microservices-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        tier: backend
        project: microservices-task
    spec:
      containers:
        - name: order-service
          image: kautikbhardwaj/order-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: SERVICE_NAME
              value: "order-service"
            - name: NODE_ENV
              value: "production"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "192Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
